



valid_amino_acids = set("A C D E F G H I K L M N P Q R S T V W Y") #ARNDCEQGHILKMFPSTWYV

protein_seq = "MSLGRLCRLLKPALLCGALAAPGLAGTMCASRDDWRCARSMHEFSAKDIDGHMVNLDKYRGFVCIVTNVASQUGKTEVNYTQLVDLHARYAECGLRILAFPCNQFGKQEPGSNEEIKEFAAGYNVKFDMFSKICVNGDDAHPLWKWMKIQPKGKGILGNAIKWNFTKFLIDKNGCVVKRYGPMEEPLVIEKDLPHYF"

if set(protein_seq).issubset(valid_amino_acids):
    print("Valid protein sequence")
else:
    print("Invalid protein sequence")



